### ISSUE TITLE
Python Packaging Tools: Lack of Windows concerns

### ISSUE THREAD

**Issue by minchinweb** [zotroneneis/zotroneneis.github.io#11]
Hi Anna-Lena!

I read your article on [Python environment management and packaging tools](https://alpopkes.com/posts/python/packaging_tools/), but was a little disappointed that Windows and cross-platform support is never mentioned. I guess this is dear to my heart because the reason I personally picked up Python (over a decade ago) is because it had better Windows support than Ruby did, and I've never looked back.

Of particular interest for your article is the [Python Launcher for Windows](https://docs.python.org/3/using/windows.html#launcher), which would fall under "Python version management" (although you have to install each Python version separately). This is automatically installed with Python on Windows

> If you have multiple versions of Python installed (e.g., 3.7 and 3.12) you will have noticed that Python 3.12 was started - to launch Python 3.7, try the command:
>
>     py -3.7
>
> If you want the latest version of Python 2 you have installed, try the command:
>
>     py -2

Beyond that, I'm also concerned/interested at how well the other tools support Windows. In general, if a tools is pure Python, concerns are minimal. However, as you reply on "standard UNIX tools" or other ecosystems (bash, make, clang, gcc, node-js, rust, etc), becomes considerably more complicated. The UNIX tools, as a rule, are simply not there. For each ecosystem, there is no simple `apt install rust` (equivalent) and instead ~4 common-ish ways to install the ecosystem (in OSS fashion), each with it's own trade-offs, to sort through and hope that the first one you pick actually works. Plus it's another ecosystem that when it breaks, I have no idea how to fix. For someone starting with Python, it's a big ask. (That said, rust has been surprisingly problem-free for Python tools, once I got it installed.)

Another type of issue that can come up with if no one on the dev team actually uses Windows. There are very few Windows idioms that you need to deal with, but one is that running `source {path_to_venv}\Script\activate.bat` won't work (on Windows, you don't `source` batch files, you can just run them directly). I bring this up as an example of something I ran into, specifically with [poetry](https://github.com/python-poetry/poetry/pull/3978), but which sat in their official documentation for ~2 years after being reported and a fix offered. Another poetry issue that I frequently ran into at the time was that the error messages would break due to Window UFT-8 handling, and so instead of a useful error message, I'd get [~100 lines of poetry errors](https://github.com/python-poetry/poetry/pull/3978).

These are hard problems, and I'm glad someone else is tackling them, but it does make me cautious of using anything without obvious declared Windows support.

Hope some of these thoughts are helpful,
- MinchinWeb

**Comment by zotroneneis** [comment]
Thanks a lot for your feedback and thoughts! I will add them to my "to do" list for an updated version of the blog post.
