### ISSUE TITLE
improve this page buttun seems broken 

### ISSUE THREAD

**Issue by DahanDv** [zotroneneis/zotroneneis.github.io#6]
I may be missing something here, but on other tutorials I've edited the experience was smooth.
I was trying to fix some slightly outdated metrics in your article:
**_An unbiased evaluation of environment management and packaging tools_**
BTW - Bravo!!! 
Clicking on the "improve this page" at the bottom right corner led me to this:

![image](https://github.com/zotroneneis/zotroneneis.github.io/assets/33809239/6bb968b4-b095-472b-b144-8914d83a301b)

**Comment by zotroneneis** [comment]
Thanks a lot, I resolved the issue!
